name: Release

on:
  workflow_dispatch:
  release:
    types:
      - created

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    environment: release
    if: ${{ github.repository }} == 'moradology/beam-pyspark-runner'
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: python -m pip install tox

      - name: Release
        run: tox -e release
        env:
          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
